version: "2.18.1"
services:

  postgres_db:
    container_name: postgres_test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=contrasena
      - POSTGRES_DB=test
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  springboot:
    container_name: springboot_data
    image: springboot
    build: .
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_test:5432/test
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=contrasena
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
